name: 'Setup Node.js'
description: 'Sets up Node.js LTS and installs dependencies'
inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: 'lts/*'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      run: npm ci
      shell: bash
